apiVersion: v1
kind: Service
metadata:
  name: ptm-todo-app-service
  labels:
    app: ptm-todo-app
spec:
  type: LoadBalancer
  selector:
    app: ptm-todo-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: None

